###############################################################################
# Travis Build
#
# Author: Najih <najih@urbanindo.com>
###############################################################################
language: php

branches:
    only:
        - master

php:
    - 7.0

install:
    - travis_retry composer self-update && composer --version
    - travis_retry composer install --prefer-dist --no-interaction

script:
    - php ./vendor/bin/phpcs --standard=ruleset.xml src/